services:
  appdb:
    image: postgres:16.2
    volumes:
      - appdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloakdemo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=senha123
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  appdb_data:
    driver: local
  pgadmin_data:
